server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    location = /wp-login.php { return 404; }
    location ^~ /wp-admin/ { return 404; }
    location = /.env { return 404; }
    location = /.git { return 404; }
    location ^~ /.git/ { return 404; }
    location = /xmlrpc.php { return 404; }

    location / {
        try_files $uri $uri/ /index.html;
    }
}
