from __future__ import annotations

import re
import unicodedata
from typing import Any


def normalize_entity_text(value: str | None) -> str:
    raw = (value or "").strip().lower()
    if not raw:
        return ""
    normalized = unicodedata.normalize("NFD", raw)
    normalized = "".join(char for char in normalized if unicodedata.category(char) != "Mn")
    normalized = re.sub(r"[^a-z0-9\s]", " ", normalized)
    return re.sub(r"\s+", " ", normalized).strip()


ENRICHED_ENTITIES: list[dict[str, Any]] = [
    {
        "name": "EPS Sura",
        "aliases": ["sura", "suramericana", "eps sura", "eps suramericana"],
        "type": "eps",
        "sector": "salud",
        "nit": "800.088.702-2",
        "address": "Cra 64B #49A-30, Medellin",
        "city": "Medellin",
        "department": "Antioquia",
        "pqrs_emails": ["eps@suramericana.com.co"],
        "legal_representative": "Gonzalo Alberto Perez Rojas",
        "superintendence": "Supersalud",
        "source": "precargada",
        "verified": True,
    },
    {
        "name": "Nueva EPS",
        "aliases": ["nueva eps", "eps nueva eps"],
        "type": "eps",
        "sector": "salud",
        "nit": "900.156.264-2",
        "address": "Calle 26 #69-76 Torre 1, Bogota",
        "city": "Bogota",
        "department": "Bogota D.C.",
        "pqrs_emails": ["notificaciones@nuevaeps.com.co", "servicioalcliente@nuevaeps.com.co"],
        "legal_representative": "Raul Cardona Zuluaga",
        "superintendence": "Supersalud",
        "source": "precargada",
        "verified": True,
    },
    {
        "name": "Sanitas EPS",
        "aliases": ["sanitas", "eps sanitas", "colsanitas"],
        "type": "eps",
        "sector": "salud",
        "nit": "800.251.440-6",
        "address": "Transv. 17 #137-45, Bogota",
        "city": "Bogota",
        "department": "Bogota D.C.",
        "pqrs_emails": ["servicioalcliente@sanitas.com.co"],
        "legal_representative": "Direccion General",
        "superintendence": "Supersalud",
        "source": "precargada",
        "verified": True,
    },
    {
        "name": "Famisanar EPS",
        "aliases": ["famisanar", "eps famisanar"],
        "type": "eps",
        "sector": "salud",
        "nit": "830.003.564-7",
        "address": "Calle 26 #68D-06, Bogota",
        "city": "Bogota",
        "department": "Bogota D.C.",
        "pqrs_emails": ["contacto@famisanar.com.co"],
        "legal_representative": "Direccion General",
        "superintendence": "Supersalud",
        "source": "precargada",
        "verified": True,
    },
    {
        "name": "Compensar EPS",
        "aliases": ["compensar", "eps compensar"],
        "type": "eps",
        "sector": "salud",
        "nit": "860.066.942-7",
        "address": "Av. 68 #49A-47, Bogota",
        "city": "Bogota",
        "department": "Bogota D.C.",
        "pqrs_emails": ["servicioalcliente@compensar.com"],
        "legal_representative": "Juan Carlos Llano",
        "superintendence": "Supersalud",
        "source": "precargada",
        "verified": True,
    },
    {
        "name": "Coosalud EPS",
        "aliases": ["coosalud", "eps coosalud"],
        "type": "eps",
        "sector": "salud",
        "nit": "900.226.715-5",
        "address": "Cra 3 #26-48, Cartagena",
        "city": "Cartagena",
        "department": "Bolivar",
        "pqrs_emails": ["contacto@coosalud.com"],
        "legal_representative": "Direccion General",
        "superintendence": "Supersalud",
        "source": "precargada",
        "verified": True,
    },
    {
        "name": "Mutual Ser EPS",
        "aliases": ["mutual ser", "eps mutual ser", "mutualser"],
        "type": "eps",
        "sector": "salud",
        "nit": "806.008.394-6",
        "address": "Cra 3 #6-31, Cartagena",
        "city": "Cartagena",
        "department": "Bolivar",
        "pqrs_emails": ["pqrs@mutualser.com"],
        "legal_representative": "Direccion General",
        "superintendence": "Supersalud",
        "source": "precargada",
        "verified": True,
    },
    {
        "name": "Capital Salud EPS",
        "aliases": ["capital salud", "eps capital salud", "capitalsalud"],
        "type": "eps",
        "sector": "salud",
        "nit": "900.298.372-9",
        "address": "Cra 7 #32-33, Bogota",
        "city": "Bogota",
        "department": "Bogota D.C.",
        "pqrs_emails": ["pqrs@capitalsalud.gov.co"],
        "legal_representative": "Direccion General",
        "superintendence": "Supersalud",
        "source": "precargada",
        "verified": True,
    },
    {
        "name": "Savia Salud EPS",
        "aliases": ["savia salud", "eps savia salud", "saviasalud"],
        "type": "eps",
        "sector": "salud",
        "nit": "900.604.350-0",
        "address": "Calle 44A #55-44, Medellin",
        "city": "Medellin",
        "department": "Antioquia",
        "pqrs_emails": ["pqrs@saviasaludeps.com"],
        "legal_representative": "Direccion General",
        "superintendence": "Supersalud",
        "source": "precargada",
        "verified": True,
    },
    {
        "name": "Emssanar EPS",
        "aliases": ["emssanar", "eps emssanar"],
        "type": "eps",
        "sector": "salud",
        "nit": "817.001.773-9",
        "address": "Cra 4 #16-57, Pasto",
        "city": "Pasto",
        "department": "Narino",
        "pqrs_emails": ["pqrs@emssanar.org.co"],
        "legal_representative": "Direccion General",
        "superintendence": "Supersalud",
        "source": "precargada",
        "verified": True,
    },
    {
        "name": "Bancolombia",
        "aliases": ["banco colombia", "bancolombia sa"],
        "type": "banco",
        "sector": "financiero",
        "nit": "890.903.938-8",
        "address": "Cra 48 #26-85, Medellin",
        "city": "Medellin",
        "department": "Antioquia",
        "pqrs_emails": ["correspon@bancolombia.com.co", "servicioalcliente@bancolombia.com.co"],
        "legal_representative": "Juan Carlos Mora Uribe",
        "superintendence": "Superfinanciera",
        "source": "precargada",
        "verified": True,
    },
    {
        "name": "Banco de Bogota",
        "aliases": ["bogota", "banco bogota"],
        "type": "banco",
        "sector": "financiero",
        "nit": "860.002.964-4",
        "address": "Calle 36 #10-55, Bogota",
        "city": "Bogota",
        "department": "Bogota D.C.",
        "pqrs_emails": ["serviciocliente@bancodebogota.com.co"],
        "legal_representative": "Alejandro Figueroa",
        "superintendence": "Superfinanciera",
        "source": "precargada",
        "verified": True,
    },
    {
        "name": "Davivienda",
        "aliases": ["banco davivienda"],
        "type": "banco",
        "sector": "financiero",
        "nit": "860.034.313-7",
        "address": "Av. El Dorado #68C-61, Bogota",
        "city": "Bogota",
        "department": "Bogota D.C.",
        "pqrs_emails": ["servicioalcliente@davivienda.com"],
        "legal_representative": "Santiago Perdomo Maldonado",
        "superintendence": "Superfinanciera",
        "source": "precargada",
        "verified": True,
    },
    {
        "name": "BBVA Colombia",
        "aliases": ["bbva", "bbva colombia"],
        "type": "banco",
        "sector": "financiero",
        "nit": "860.003.020-1",
        "address": "Cra 9 #72-21, Bogota",
        "city": "Bogota",
        "department": "Bogota D.C.",
        "pqrs_emails": ["bbvacolombia@bbva.com"],
        "legal_representative": "Mario Pardo",
        "superintendence": "Superfinanciera",
        "source": "precargada",
        "verified": True,
    },
    {
        "name": "Banco de Occidente",
        "aliases": ["occidente", "banco occidente"],
        "type": "banco",
        "sector": "financiero",
        "nit": "890.300.279-4",
        "address": "Calle 25AN #6N-62, Cali",
        "city": "Cali",
        "department": "Valle del Cauca",
        "pqrs_emails": ["servicioalcliente@bancodeoccidente.com.co"],
        "legal_representative": "Efrain Otero",
        "superintendence": "Superfinanciera",
        "source": "precargada",
        "verified": True,
    },
    {
        "name": "Banco Popular",
        "aliases": ["popular", "banco popular"],
        "type": "banco",
        "sector": "financiero",
        "nit": "860.007.738-9",
        "address": "Calle 17 #7-43, Bogota",
        "city": "Bogota",
        "department": "Bogota D.C.",
        "pqrs_emails": ["servicioalcliente@bancopopular.com.co"],
        "legal_representative": "Direccion General",
        "superintendence": "Superfinanciera",
        "source": "precargada",
        "verified": True,
    },
    {
        "name": "Scotiabank Colpatria",
        "aliases": ["colpatria", "scotiabank", "scotiabank colpatria"],
        "type": "banco",
        "sector": "financiero",
        "nit": "860.034.594-0",
        "address": "Cra 7 #24-89, Bogota",
        "city": "Bogota",
        "department": "Bogota D.C.",
        "pqrs_emails": ["servicioalcliente@colpatria.com"],
        "legal_representative": "Direccion General",
        "superintendence": "Superfinanciera",
        "source": "precargada",
        "verified": True,
    },
    {
        "name": "Banco Agrario",
        "aliases": ["agrario", "banco agrario de colombia"],
        "type": "banco",
        "sector": "financiero",
        "nit": "800.037.800-8",
        "address": "Cra 8 #15-43, Bogota",
        "city": "Bogota",
        "department": "Bogota D.C.",
        "pqrs_emails": ["servicioalcliente@bancoagrario.gov.co"],
        "legal_representative": "Direccion General",
        "superintendence": "Superfinanciera",
        "source": "precargada",
        "verified": True,
    },
    {
        "name": "Nequi",
        "aliases": ["nequi bancolombia"],
        "type": "fintech",
        "sector": "financiero",
        "nit": "890.903.938-8",
        "address": "Cra 48 #26-85, Medellin",
        "city": "Medellin",
        "department": "Antioquia",
        "pqrs_emails": ["ayuda@nequi.com.co"],
        "legal_representative": "Ver Bancolombia",
        "superintendence": "Superfinanciera",
        "source": "precargada",
        "verified": True,
    },
    {
        "name": "Nu Colombia",
        "aliases": ["nu", "nubank colombia"],
        "type": "fintech",
        "sector": "financiero",
        "nit": "901.656.780-3",
        "address": "Bogota",
        "city": "Bogota",
        "department": "Bogota D.C.",
        "pqrs_emails": ["soporte@nu.com.co"],
        "legal_representative": "Direccion General",
        "superintendence": "Superfinanciera",
        "source": "precargada",
        "verified": True,
    },
    {
        "name": "Claro (Comcel)",
        "aliases": ["claro", "comcel"],
        "type": "telecom",
        "sector": "telecomunicaciones",
        "nit": "800.153.993-7",
        "pqrs_emails": ["servicioalcliente@claro.com.co"],
        "superintendence": "SIC / CRC",
        "source": "precargada",
        "verified": True,
    },
    {
        "name": "Movistar (Telefonica)",
        "aliases": ["movistar", "telefonica"],
        "type": "telecom",
        "sector": "telecomunicaciones",
        "nit": "800.153.993-7",
        "pqrs_emails": ["servicioalcliente@movistar.com.co"],
        "superintendence": "SIC / CRC",
        "source": "precargada",
        "verified": True,
    },
    {
        "name": "Tigo (Colombia Movil)",
        "aliases": ["tigo", "colombia movil"],
        "type": "telecom",
        "sector": "telecomunicaciones",
        "nit": "830.114.921-9",
        "pqrs_emails": ["pqrs@tigo.com.co"],
        "superintendence": "SIC / CRC",
        "source": "precargada",
        "verified": True,
    },
    {
        "name": "WOM",
        "aliases": ["wom colombia"],
        "type": "telecom",
        "sector": "telecomunicaciones",
        "nit": "901.540.563-4",
        "pqrs_emails": ["pqrs@wom.co"],
        "superintendence": "SIC / CRC",
        "source": "precargada",
        "verified": True,
    },
    {
        "name": "ETB",
        "aliases": ["empresa de telecomunicaciones de bogota"],
        "type": "telecom",
        "sector": "telecomunicaciones",
        "nit": "899.999.115-8",
        "pqrs_emails": ["pqrs@etb.com.co"],
        "superintendence": "SIC / CRC",
        "source": "precargada",
        "verified": True,
    },
    {
        "name": "EPM",
        "aliases": ["empresas publicas de medellin"],
        "type": "servicio_publico",
        "sector": "energia, agua y gas",
        "nit": "890.904.996-1",
        "pqrs_emails": ["pqrs@epm.com.co"],
        "superintendence": "Superservicios",
        "source": "precargada",
        "verified": True,
    },
    {
        "name": "Enel (Codensa)",
        "aliases": ["enel", "codensa"],
        "type": "servicio_publico",
        "sector": "energia electrica",
        "nit": "830.037.248-0",
        "pqrs_emails": ["pqrs@enel.com"],
        "superintendence": "Superservicios",
        "source": "precargada",
        "verified": True,
    },
    {
        "name": "Vanti (Gas Natural)",
        "aliases": ["vanti", "gas natural"],
        "type": "servicio_publico",
        "sector": "gas natural",
        "nit": "800.216.181-7",
        "pqrs_emails": ["pqrs@vfrgroup.co"],
        "superintendence": "Superservicios",
        "source": "precargada",
        "verified": True,
    },
    {
        "name": "Acueducto de Bogota",
        "aliases": ["eaab", "acueducto bogota", "empresa de acueducto de bogota"],
        "type": "servicio_publico",
        "sector": "agua y alcantarillado",
        "nit": "899.999.094-1",
        "pqrs_emails": ["pqrs@acueducto.com.co"],
        "superintendence": "Superservicios",
        "source": "precargada",
        "verified": True,
    },
    {
        "name": "Air-e",
        "aliases": ["aire"],
        "type": "servicio_publico",
        "sector": "energia electrica",
        "nit": "900.351.317-4",
        "pqrs_emails": ["pqrs@air-e.com"],
        "superintendence": "Superservicios",
        "source": "precargada",
        "verified": True,
    },
    {
        "name": "Afinia",
        "aliases": ["afinia grupo epm"],
        "type": "servicio_publico",
        "sector": "energia electrica",
        "nit": "900.351.315-0",
        "pqrs_emails": ["pqrs@afinia.com.co"],
        "superintendence": "Superservicios",
        "source": "precargada",
        "verified": True,
    },
    {
        "name": "Supersalud",
        "aliases": ["super salud", "superintendencia nacional de salud"],
        "type": "gobierno",
        "sector": "control",
        "address": "Cra 7 #32-16, Bogota",
        "city": "Bogota",
        "department": "Bogota D.C.",
        "pqrs_emails": ["contactenos@supersalud.gov.co"],
        "website": "https://www.supersalud.gov.co",
        "superintendence": "Supersalud",
        "source": "precargada",
        "verified": True,
    },
    {
        "name": "Superfinanciera",
        "aliases": ["superintendencia financiera", "sfc"],
        "type": "gobierno",
        "sector": "control",
        "address": "Calle 7 #4-49, Bogota",
        "city": "Bogota",
        "department": "Bogota D.C.",
        "pqrs_emails": ["super@superfinanciera.gov.co"],
        "website": "https://www.superfinanciera.gov.co",
        "superintendence": "Superfinanciera",
        "source": "precargada",
        "verified": True,
    },
    {
        "name": "SIC",
        "aliases": ["superintendencia de industria y comercio"],
        "type": "gobierno",
        "sector": "control",
        "address": "Cra 13 #27-00, Bogota",
        "city": "Bogota",
        "department": "Bogota D.C.",
        "pqrs_emails": ["contactenos@sic.gov.co"],
        "website": "https://www.sic.gov.co",
        "superintendence": "SIC",
        "source": "precargada",
        "verified": True,
    },
    {
        "name": "Superservicios",
        "aliases": ["superintendencia de servicios publicos"],
        "type": "gobierno",
        "sector": "control",
        "address": "Cra 18 #84-35, Bogota",
        "city": "Bogota",
        "department": "Bogota D.C.",
        "pqrs_emails": ["contactenos@superservicios.gov.co"],
        "website": "https://www.superservicios.gov.co",
        "superintendence": "Superservicios",
        "source": "precargada",
        "verified": True,
    },
    {
        "name": "Mintrabajo",
        "aliases": ["ministerio del trabajo"],
        "type": "gobierno",
        "sector": "ministerio",
        "address": "Cra 7 #31-10, Bogota",
        "city": "Bogota",
        "department": "Bogota D.C.",
        "pqrs_emails": ["servicioalciudadano@mintrabajo.gov.co"],
        "website": "https://www.mintrabajo.gov.co",
        "source": "precargada",
        "verified": True,
    },
    {
        "name": "Procuraduria",
        "aliases": ["procuraduria general", "procuraduria general de la nacion"],
        "type": "gobierno",
        "sector": "control",
        "address": "Cra 5 #15-80, Bogota",
        "city": "Bogota",
        "department": "Bogota D.C.",
        "pqrs_emails": ["quejas@procuraduria.gov.co"],
        "website": "https://www.procuraduria.gov.co",
        "source": "precargada",
        "verified": True,
    },
    {
        "name": "Defensoria del Pueblo",
        "aliases": ["defensoria", "defensoria pueblo"],
        "type": "gobierno",
        "sector": "defensa",
        "address": "Calle 55 #10-32, Bogota",
        "city": "Bogota",
        "department": "Bogota D.C.",
        "pqrs_emails": ["servicioalciudadano@defensoria.gov.co"],
        "website": "https://www.defensoria.gov.co",
        "source": "precargada",
        "verified": True,
    },
    {
        "name": "Minsalud",
        "aliases": ["ministerio de salud", "ministerio de salud y proteccion social"],
        "type": "gobierno",
        "sector": "ministerio",
        "address": "Cra 13 #32-76, Bogota",
        "city": "Bogota",
        "department": "Bogota D.C.",
        "pqrs_emails": ["atencionalciudadano@minsalud.gov.co"],
        "website": "https://www.minsalud.gov.co",
        "source": "precargada",
        "verified": True,
    },
]


for entity in ENRICHED_ENTITIES:
    entity["name_search"] = normalize_entity_text(entity["name"])
    entity["aliases_search"] = [normalize_entity_text(alias) for alias in entity.get("aliases", [])]


def search_enriched_entities(query: str, limit: int = 8) -> list[dict[str, Any]]:
    normalized_query = normalize_entity_text(query)
    if len(normalized_query) < 2:
        return []

    matches: list[tuple[int, dict[str, Any]]] = []
    for entity in ENRICHED_ENTITIES:
        candidates = [entity["name_search"], *entity.get("aliases_search", [])]
        if normalized_query in candidates:
            score = 0
        elif any(candidate.startswith(normalized_query) for candidate in candidates):
            score = 1
        elif any(normalized_query in candidate for candidate in candidates):
            score = 2
        else:
            continue
        matches.append((score, entity))

    matches.sort(key=lambda item: (item[0], item[1]["name"]))
    return [dict(entity) for _, entity in matches[:limit]]
